BUFFER_SIZE_VERY_SMALL=1024
BUFFER_SIZE_SMALL=4096
BUFFER_SIZE_MEDIUM=16384
BUFFER_SIZE_LARGE=65536
BUFFER_SIZE_VERY_LARGE=16777216

FILE_NAME_ACK="FILENAMEACK\n"
REQUEST_TO_SEND="REQUEST_TO_SEND\n"
ALLOW_TO_RECV="ALLOW_TO_RECV\n"
NOT_ALLOW_TO_RECV="NOT_ALLOW_TO_RECV\n"
CONNECTION_ESTABLISHED_SERVER="CONNECTION_ESTABLISHED_SERVER_ACK\n"
CONNECTION_ESTABLISHED_CLIENT="CONNECTION_ESTABLISHED_CLIENT_ACK\n"
RECEIVING_ACK="RECEIVING_ACK\n";
CONNECTION_ERROR="CONNECTION_ERROR"

TEST_STRING="THIS IS THE TEST STRING WHICH IS USED TO SEE WEATHER THE ORDER OF THE BYTES REACHING THE CLIENT IS IN THE RIGHT ORDER OR NOT FOR TWO SOCKET SYSTEM"


BASEPATH="WifiDocs\\"

SEPARATOR="-_-"